# Workflow name
name: CI/CD Jukebox
on:
  # Manually trigger workflow runs
  workflow_dispatch:
  # Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:

  # Test's job
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    # Job's steps
    steps:
      
      # Check-out
      - uses: actions/checkout@v2 

      # Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      # Set up Maven cache
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      # Run Tests
      - name: Run Tests
        run: mvn -B test

  # Build's job
  build:
    name: Build Project
    needs: tests
    runs-on: ubuntu-latest

    # Job's steps
    steps:
      
      # Check-out
      - uses: actions/checkout@v2 

      # Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      # Set up Maven cache
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      # Build project
      - name: Build project
        run: mvn -B package -DskipTests

      # Upload JAR
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/*.jar
  
  # Publish to Docker Hub job
  build-and-push-image:
    name: Build and Push Docker image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Check-out
      - uses: actions/checkout@v2 

      # Upload JAR
      - name: Download artifact
        uses: actions/download-artifact@v3
      
      # Unzip artifact and move JAR to the right Directory
      - name: Move Jar to right directory
        run: |
          ls
          ls artifact/
          mv artifact/juckboxSettings-*.jar target/
      
      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and Publish Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: imadsa/juckboxSettings:latest