steps:

  # Test
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'test' ]
    id: 'test'

  # Package
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'package', '-DskipTests' ]
    wait_for: [ 'test' ]
    id: 'package'

  # Create Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/jukebox', '.' ]
    wait_for: [ 'package' ]

images:
  - 'gcr.io/$PROJECT_ID/jukebox'
