# Workflow name
name: CI/CD Jukebox
on:
  # Manually trigger workflow runs
  workflow_dispatch:
  # Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:

  # Test's and Build's job
  test-build:
    name: Run tests and Build
    runs-on: ubuntu-latest

    # Job's steps
    steps:
      
      # Check-out
      - uses: actions/checkout@v2 

      # Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      # Set up Maven cache
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      # Run Tests
      - name: Run Tests
        run: mvn test

      # Build and Analyze project
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ImadSai_jukebox

  # Creating environement
  creating-environement:
    name: create enviroenement

    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-11-slim

    # Job's steps
    steps:
      
      # Check-out
      - uses: actions/checkout@v2 